import {
  GetDsosActions,
  GetEscrowStatusActions,
  GetMembersActions,
  GetProposalActions,
  GetProposalsActions,
} from "./queries";

export * from "./queries";

export enum DsosActionTypes {
  GET_DSOS_REQUEST = "GET_DSOS_REQUEST",
  GET_DSOS_SUCCESS = "GET_DSOS_SUCCESS",

  GET_ESCROW_STATUS_REQUEST = "GET_ESCROW_STATUS_REQUEST",
  GET_ESCROW_STATUS_SUCCESS = "GET_ESCROW_STATUS_SUCCESS",
  GET_ESCROW_STATUS_FAILURE = "GET_ESCROW_STATUS_FAILURE",

  GET_MEMBERS_REQUEST = "GET_MEMBERS_REQUEST",
  GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS",
  GET_MEMBERS_FAILURE = "GET_MEMBERS_FAILURE",

  GET_PROPOSALS_REQUEST = "GET_PROPOSALS_REQUEST",
  GET_PROPOSALS_SUCCESS = "GET_PROPOSALS_SUCCESS",
  GET_PROPOSALS_FAILURE = "GET_PROPOSALS_FAILURE",

  GET_PROPOSAL_REQUEST = "GET_PROPOSAL_REQUEST",
  GET_PROPOSAL_SUCCESS = "GET_PROPOSAL_SUCCESS",
  GET_PROPOSAL_FAILURE = "GET_PROPOSAL_FAILURE",
}

export type DsosActions =
  | GetDsosActions
  | GetEscrowStatusActions
  | GetMembersActions
  | GetProposalsActions
  | GetProposalActions;
